[2023-11-24 17:35:19,175] INFO _log() L224  [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5001 - call_trace=C:\Users\moacy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\werkzeug\_internal.py L224 
[2023-11-24 17:35:19,179] INFO _log() L224  [33mPress CTRL+C to quit[0m - call_trace=C:\Users\moacy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\werkzeug\_internal.py L224 
[2023-11-24 17:35:19,182] INFO _log() L224   * Restarting with stat - call_trace=C:\Users\moacy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\werkzeug\_internal.py L224 
[2023-11-24 17:35:19,890] WARNING _log() L224   * Debugger is active! - call_trace=C:\Users\moacy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\werkzeug\_internal.py L224 
[2023-11-24 17:35:19,894] INFO _log() L224   * Debugger PIN: 738-487-147 - call_trace=C:\Users\moacy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\werkzeug\_internal.py L224 
[2023-11-24 17:35:37,882] INFO _log() L224  127.0.0.1 - - [24/Nov/2023 17:35:37] "OPTIONS /AvalFIMult?resgate=1&capta=2&cotistas=1000&patliq=1000000&quota=5 HTTP/1.1" 200 - - call_trace=C:\Users\moacy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\werkzeug\_internal.py L224 
[2023-11-24 17:35:47,921] INFO _log() L224  127.0.0.1 - - [24/Nov/2023 17:35:47] "[35m[1mGET /AvalFIMult?resgate=1&capta=2&cotistas=1000&patliq=1000000&quota=5 HTTP/1.1[0m" 500 - - call_trace=C:\Users\moacy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\werkzeug\_internal.py L224 
[2023-11-24 17:44:16,531] INFO _log() L224  [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5001 - call_trace=C:\Users\moacy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\werkzeug\_internal.py L224 
[2023-11-24 17:44:16,532] INFO _log() L224  [33mPress CTRL+C to quit[0m - call_trace=C:\Users\moacy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\werkzeug\_internal.py L224 
[2023-11-24 17:44:16,533] INFO _log() L224   * Restarting with stat - call_trace=C:\Users\moacy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\werkzeug\_internal.py L224 
[2023-11-24 17:44:17,336] WARNING _log() L224   * Debugger is active! - call_trace=C:\Users\moacy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\werkzeug\_internal.py L224 
[2023-11-24 17:44:17,340] INFO _log() L224   * Debugger PIN: 738-487-147 - call_trace=C:\Users\moacy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\werkzeug\_internal.py L224 
[2023-11-24 17:44:42,800] INFO _log() L224  127.0.0.1 - - [24/Nov/2023 17:44:42] "OPTIONS /AvalFIMult?resgate=1&capta=2&cotistas=1000&patliq=1000000&quota=5 HTTP/1.1" 200 - - call_trace=C:\Users\moacy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\werkzeug\_internal.py L224 
[2023-11-24 17:44:45,581] INFO _log() L224  127.0.0.1 - - [24/Nov/2023 17:44:45] "[35m[1mGET /AvalFIMult?resgate=1&capta=2&cotistas=1000&patliq=1000000&quota=5 HTTP/1.1[0m" 500 - - call_trace=C:\Users\moacy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\werkzeug\_internal.py L224 
