[2023-12-03 14:09:05,724] INFO _log() L224   * Restarting with stat - call_trace=C:\Users\moacy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\werkzeug\_internal.py L224 
[2023-12-03 14:09:07,769] WARNING _log() L224   * Debugger is active! - call_trace=C:\Users\moacy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\werkzeug\_internal.py L224 
[2023-12-03 14:09:07,774] INFO _log() L224   * Debugger PIN: 738-487-147 - call_trace=C:\Users\moacy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\werkzeug\_internal.py L224 
[2023-12-03 14:09:15,251] INFO _log() L224  [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5001 - call_trace=C:\Users\moacy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\werkzeug\_internal.py L224 
[2023-12-03 14:09:15,252] INFO _log() L224  [33mPress CTRL+C to quit[0m - call_trace=C:\Users\moacy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\werkzeug\_internal.py L224 
[2023-12-03 14:09:15,253] INFO _log() L224   * Restarting with stat - call_trace=C:\Users\moacy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\werkzeug\_internal.py L224 
[2023-12-03 14:09:17,070] WARNING _log() L224   * Debugger is active! - call_trace=C:\Users\moacy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\werkzeug\_internal.py L224 
[2023-12-03 14:09:17,076] INFO _log() L224   * Debugger PIN: 738-487-147 - call_trace=C:\Users\moacy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\werkzeug\_internal.py L224 
[2023-12-03 14:09:20,157] INFO _log() L224  127.0.0.1 - - [03/Dec/2023 14:09:20] "GET /avalfimult?resgate=1&capta=2&patliq=1000000&pattotal=4 HTTP/1.1" 200 - - call_trace=C:\Users\moacy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\werkzeug\_internal.py L224 
[2023-12-03 14:09:30,645] INFO _log() L224  127.0.0.1 - - [03/Dec/2023 14:09:30] "GET /avalfimult?resgate=1&capta=2&patliq=1000000&pattotal=4 HTTP/1.1" 200 - - call_trace=C:\Users\moacy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\werkzeug\_internal.py L224 
[2023-12-03 14:09:41,782] INFO _log() L224   * Detected change in 'C:\\venv\\.__Projetos\\PUC_EngSoft_MVP4\\back\\avalfimult.py', reloading - call_trace=C:\Users\moacy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\werkzeug\_internal.py L224 
[2023-12-03 14:09:42,114] INFO _log() L224   * Restarting with stat - call_trace=C:\Users\moacy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\werkzeug\_internal.py L224 
[2023-12-03 14:09:43,928] WARNING _log() L224   * Debugger is active! - call_trace=C:\Users\moacy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\werkzeug\_internal.py L224 
[2023-12-03 14:09:43,932] INFO _log() L224   * Debugger PIN: 738-487-147 - call_trace=C:\Users\moacy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\werkzeug\_internal.py L224 
[2023-12-03 14:10:37,751] INFO _log() L224   * Detected change in 'C:\\venv\\.__Projetos\\PUC_EngSoft_MVP4\\back\\AvalFIMult.py', reloading - call_trace=C:\Users\moacy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\werkzeug\_internal.py L224 
[2023-12-03 14:10:38,145] INFO _log() L224   * Restarting with stat - call_trace=C:\Users\moacy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\werkzeug\_internal.py L224 
[2023-12-03 14:10:40,519] WARNING _log() L224   * Debugger is active! - call_trace=C:\Users\moacy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\werkzeug\_internal.py L224 
[2023-12-03 14:10:40,525] INFO _log() L224   * Debugger PIN: 738-487-147 - call_trace=C:\Users\moacy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\werkzeug\_internal.py L224 
[2023-12-03 14:10:42,506] INFO _log() L224  127.0.0.1 - - [03/Dec/2023 14:10:42] "[35m[1mGET /avalfimult?resgate=1&capta=2&patliq=1000000&pattotal=4 HTTP/1.1[0m" 500 - - call_trace=C:\Users\moacy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\werkzeug\_internal.py L224 
[2023-12-03 14:10:42,609] INFO _log() L224  127.0.0.1 - - [03/Dec/2023 14:10:42] "GET /avalfimult?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 - - call_trace=C:\Users\moacy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\werkzeug\_internal.py L224 
[2023-12-03 14:10:42,749] INFO _log() L224  127.0.0.1 - - [03/Dec/2023 14:10:42] "GET /avalfimult?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 - - call_trace=C:\Users\moacy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\werkzeug\_internal.py L224 
[2023-12-03 14:10:43,096] INFO _log() L224  127.0.0.1 - - [03/Dec/2023 14:10:43] "GET /avalfimult?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 - - call_trace=C:\Users\moacy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\werkzeug\_internal.py L224 
[2023-12-03 14:10:43,349] INFO _log() L224  127.0.0.1 - - [03/Dec/2023 14:10:43] "[36mGET /avalfimult?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 - - call_trace=C:\Users\moacy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\werkzeug\_internal.py L224 
[2023-12-03 14:13:07,726] INFO _log() L224   * Detected change in 'C:\\venv\\.__Projetos\\PUC_EngSoft_MVP4\\back\\AvalFIMult.py', reloading - call_trace=C:\Users\moacy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\werkzeug\_internal.py L224 
[2023-12-03 14:13:08,131] INFO _log() L224   * Restarting with stat - call_trace=C:\Users\moacy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\werkzeug\_internal.py L224 
[2023-12-03 14:13:10,359] WARNING _log() L224   * Debugger is active! - call_trace=C:\Users\moacy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\werkzeug\_internal.py L224 
[2023-12-03 14:13:10,365] INFO _log() L224   * Debugger PIN: 738-487-147 - call_trace=C:\Users\moacy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\werkzeug\_internal.py L224 
[2023-12-03 14:13:11,955] INFO _log() L224  127.0.0.1 - - [03/Dec/2023 14:13:11] "GET /avalfimult?resgate=1&capta=2&patliq=1000000&pattotal=4 HTTP/1.1" 200 - - call_trace=C:\Users\moacy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\werkzeug\_internal.py L224 
[2023-12-03 14:14:14,208] INFO _log() L224   * Detected change in 'C:\\venv\\.__Projetos\\PUC_EngSoft_MVP4\\back\\AvalFIMult.py', reloading - call_trace=C:\Users\moacy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\werkzeug\_internal.py L224 
[2023-12-03 14:14:14,706] INFO _log() L224   * Restarting with stat - call_trace=C:\Users\moacy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\werkzeug\_internal.py L224 
[2023-12-03 14:14:16,869] WARNING _log() L224   * Debugger is active! - call_trace=C:\Users\moacy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\werkzeug\_internal.py L224 
[2023-12-03 14:14:16,874] INFO _log() L224   * Debugger PIN: 738-487-147 - call_trace=C:\Users\moacy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\werkzeug\_internal.py L224 
[2023-12-03 14:14:17,447] INFO _log() L224  127.0.0.1 - - [03/Dec/2023 14:14:17] "[35m[1mGET /avalfimult?resgate=1&capta=2&patliq=1000000&pattotal=4 HTTP/1.1[0m" 500 - - call_trace=C:\Users\moacy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\werkzeug\_internal.py L224 
[2023-12-03 14:14:17,548] INFO _log() L224  127.0.0.1 - - [03/Dec/2023 14:14:17] "[36mGET /avalfimult?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 - - call_trace=C:\Users\moacy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\werkzeug\_internal.py L224 
